name: Let me learn github actions
on:                                        ##used for trigger 
  push:                                    ##trigger method
jobs:
  hello:
     runs-on: ubuntu-22.04                 ##github repo/local machine/any
